# silver-fox (Dell XPS 15 9500) — touchpad, no left_handed.
input {
  kb_layout = us
  kb_options = compose:caps
  repeat_rate = 40
  repeat_delay = 600
  touchpad {
    natural_scroll = true
    clickfinger_behavior = true   # two-finger = right click
    scroll_factor = 0.4
  }
}
cursor { hide_on_key_press = true }
misc  { focus_on_activate = true  mouse_move_focuses_monitor = false }
