# note: mold and clang must be installed:
# pacman -S install mold clang

[build]
jobs = 10

# ie ms surface wsl
[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-C", "link-arg=-Wl,--thread-count=10"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "-C", "link-arg=-Wl,--thread-count=10"]

[target.aarch64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
