# blackboy (desktop) — HDMI-A-1 + DP-2 ultrawide, workspaces pinned.
# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

# Straight 1x setup for low-resolution displays like 1080p or 1440p
env = GDK_SCALE,1

monitorv2 {
  output = HDMI-A-1
  mode = 1920x1080@60
  position = -1920x0
  scale = 1
  transform = 0
}

# ultrawide
monitorv2 {
  output = DP-2
  mode = 5120x1440@119.97
  position = 0x0
  scale = 1.25
  #scale = 1.333333
  transform = 0
  # additional settings
  #bitdepth = 10
  #cm = hdr
  sdrbrightness = 1.2
  sdrsaturation = 1.0
}

workspace = 1,name:beet,monitor:DP-2
workspace = 2,monitor:DP-2
workspace = 3,monitor:DP-2
workspace = 4,monitor:DP-2
workspace = 5,monitor:DP-2
workspace = 6,monitor:DP-2
workspace = 7,monitor:HDMI-A-1,layoutopt:orientation:left
workspace = 8,monitor:HDMI-A-1,layoutopt:orientation:left
workspace = 9,monitor:HDMI-A-1,layoutopt:orientation:left
workspace = 10,monitor:HDMI-A-1,layoutopt:orientation:left
